import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;


public class HelloWorld extends HttpServlet {

   public HelloWorld(){
      System.out.println("Helloword loaded");
   }
 
   private String message;
   public void doGet(HttpServletRequest request, HttpServletResponse response)
      throws ServletException, IOException {
     	   message = "HTTP/1.1 200 OK\r\n"+
				"Content-Type: text/html\r\n"+
				"Content-Length: 65\r\n" +
				"\r\n"+
	   			"<h1>Hi!! This is a dynamic content generated by a servlet ...</h1>";
      PrintWriter out = response.getWriter();
      out.println(message);
      
   }
}